/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

struct REQUEST *
get_number_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
	static struct REQUEST  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
bakery_service_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
